language: scala
jdk:
- oraclejdk8
scala:
- 2.11.8
sudo: false
install: ci/bootstrap.sh
script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
after_success: bash <(curl -s https://codecov.io/bash)
deploy:
  skip_cleanup: true
  provider: script
  script: sbt ++$TRAVIS_SCALA_VERSION publish
  on:
    tags: true
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" -delete
- find $HOME/.sbt -name "*.lock" -delete
